### ISSUE TITLE
Imported Vars

### ISSUE THREAD

**Issue by asawilliams** [MaciekBaron/sublime-list-stylesheet-vars#9] opened 2013-07-10 18:04 UTC
It would be nice if it would show the variables that are imported into the file.  Best practices are to import your global vars.

**Comment by MaciekBaron** [comment] 2013-07-10 18:41
Sorry, I'm not entirely sure what you mean? The plugin already displays imported variables, do you mean it should indicate which variables were imported and which were not?

**Comment by asawilliams** [comment] 2013-07-10 19:50
I guess it's not working for me because my vars are not directly in the imported scss file but one layer deeper.  So, it would need to follow deeper than one layer of imports.  _vars.scss (included in)-> _base.scss (included in)-> main.scss for it to work for me.

**Comment by MaciekBaron** [comment] 2013-07-10 19:51
Yes, the plugin isn't doing recursive searching.

**Comment by rodrigoAbril** [comment] 2014-01-17 05:57
Not working for me in sublime 3 :(

in my _vars.scss file works like a charm

on my main.css
@import "vars" == nothing :(

**Comment by MaciekBaron** [comment] 2014-01-17 09:42
Do you mean `main.scss`? The plugin should work with partials, I've just tested it. Please check your settings.

**Comment by fatuk** [comment] 2014-03-30 10:37
Not working with imported vars in stylus. It works only in the same file that vars were declared.

``` stylus
@import 'vars'
.content
    width 980px
    background $my-red
....
```

vars.styl

``` stylus
$my-red = #f00
```

**Comment by MaciekBaron** [comment] 2014-04-01 08:52
Thanks for the report @fatuk , I remember testing Stylus so not sure what's wrong (of the top of my head, perhaps you're importing a file without specifying the extension and I haven't implemented support for such behaviour).

I'll try to fix this whenever I get a moment.

**Comment by fatuk** [comment] 2014-04-01 10:11
I've tested case when I import with extension. It doesn't work.
Thanks for answer.

**Comment by MaciekBaron** [comment] 2014-04-07 10:14
@fatuk, the issue is with single quotation marks `'`, if you use double `"` it works. I'll fix this in a moment.

**Comment by MaciekBaron** [comment] 2014-04-07 10:29
I've fixed that now @fatuk, I think there are no other issues related to importing files so I will close this issue for now. Feel free to re-open or create a new issue if there are any other problems.

**Closed as completed by MaciekBaron** 2014-04-07 10:29 UTC
